name: tox
on: [push, pull_request]
jobs:
  tox:
    strategy:
      fail-fast: false
      # max-parallel: 6
      matrix:
        os: [ubuntu-latest]  # [macos-latest, ubuntu-latest, windows-latest]
        job: ['py38-django3213', 'py39-django3213', 'py310-django3213', 'py38-django404', 'py39-django404', 'py310-django404']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        if: ${{ startswith(matrix.job, 'py38') }}
        with:
          python-version: '3.8'
      - uses: actions/setup-python@v4
        if: ${{ startswith(matrix.job, 'py39') }}
        with:
          python-version: '3.9'
      - uses: actions/setup-python@v4
        if: ${{ startswith(matrix.job, 'py310') }}
        with:
          python-version: '3.10'
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: pip install "coverage>=3.7.1" coveralls
      - run: tox -e ${{ matrix.job }}
      - run: coverage report
      - run: coveralls
